amazon:
  aws:
    accesskey: test
    region: eu-central-1
    secretkey: test
  dynamodb:
    endpoint: 'http://localhost:4566/'
server:
  port: 8888
spring:
  application:
    name: donation-server
twitter:
  api:
    clientid: y7A7dhU8o193NCmHqjsUSYnNZ
    secret: Es22IHfi2zQRjIyxbhvg8wSGKzeNbvS4uisQpCzXe0RyT6nobH
    callback: http://social-diamond.legendary-api.gg/twitterCallback
    token:
      request: http://social-diamond.legendary-api.gg/getToken
env: local