amazon:
  aws:
    accesskey: test
    region: eu-central-1
    secretkey: test
  dynamodb:
    endpoint: 'http://dynamodb.us-east-1.amazonaws.com/'
server:
  port: 8888
  env: prod
spring:
  application:
    name: donation-server
    url: https://social-diamond.legendary-api.com/
twitter:
  api:
    clientid: y7A7dhU8o193NCmHqjsUSYnNZ
    secret: Es22IHfi2zQRjIyxbhvg8wSGKzeNbvS4uisQpCzXe0RyT6nobH
    callback: https://social-diamond.legendary-api.com/twitterCallback
    token:
      request: https://social-diamond.legendary-api.com/getToken