amazon:
  aws:
    accesskey: test
    region: eu-central-1
    secretkey: test
  dynamodb:
    endpoint: 'http://dynamodb.us-east-1.amazonaws.com/'
server:
  port: 8888
  env: local
spring:
  application:
    name: donation-server
    url: http://localhost:8888/
twitter:
  api:
    clientid: y7A7dhU8o193NCmHqjsUSYnNZ
    secret: Es22IHfi2zQRjIyxbhvg8wSGKzeNbvS4uisQpCzXe0RyT6nobH
    callback: http://localhost:8888/twitterCallback
    token:
      request: http://localhost:8888/getToken